//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFM.SFMWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SFMWebservice.SFMConsultingWebServiceSoap")]
    public interface SFMConsultingWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterVisitorUser", ReplyAction="*")]
        SFM.SFMWebservice.RegisterVisitorUserResponse RegisterVisitorUser(SFM.SFMWebservice.RegisterVisitorUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterVisitorUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.RegisterVisitorUserResponse> RegisterVisitorUserAsync(SFM.SFMWebservice.RegisterVisitorUserRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUser", ReplyAction="*")]
        SFM.SFMWebservice.LoginUserResponse LoginUser(SFM.SFMWebservice.LoginUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginUserResponse> LoginUserAsync(SFM.SFMWebservice.LoginUserRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAdmin", ReplyAction="*")]
        SFM.SFMWebservice.LoginAdminResponse LoginAdmin(SFM.SFMWebservice.LoginAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginAdminResponse> LoginAdminAsync(SFM.SFMWebservice.LoginAdminRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginManager", ReplyAction="*")]
        SFM.SFMWebservice.LoginManagerResponse LoginManager(SFM.SFMWebservice.LoginManagerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginManager", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginManagerResponse> LoginManagerAsync(SFM.SFMWebservice.LoginManagerRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginConsultant", ReplyAction="*")]
        SFM.SFMWebservice.LoginConsultantResponse LoginConsultant(SFM.SFMWebservice.LoginConsultantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginConsultant", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginConsultantResponse> LoginConsultantAsync(SFM.SFMWebservice.LoginConsultantRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCustomer", ReplyAction="*")]
        SFM.SFMWebservice.LoginCustomerResponse LoginCustomer(SFM.SFMWebservice.LoginCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginCustomerResponse> LoginCustomerAsync(SFM.SFMWebservice.LoginCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name EmpType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterEmployee", ReplyAction="*")]
        SFM.SFMWebservice.RegisterEmployeeResponse RegisterEmployee(SFM.SFMWebservice.RegisterEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.RegisterEmployeeResponse> RegisterEmployeeAsync(SFM.SFMWebservice.RegisterEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name EmpType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveEmployee", ReplyAction="*")]
        SFM.SFMWebservice.RemoveEmployeeResponse RemoveEmployee(SFM.SFMWebservice.RemoveEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.RemoveEmployeeResponse> RemoveEmployeeAsync(SFM.SFMWebservice.RemoveEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name EmpType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditEmployeeInformation", ReplyAction="*")]
        SFM.SFMWebservice.EditEmployeeInformationResponse EditEmployeeInformation(SFM.SFMWebservice.EditEmployeeInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditEmployeeInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<SFM.SFMWebservice.EditEmployeeInformationResponse> EditEmployeeInformationAsync(SFM.SFMWebservice.EditEmployeeInformationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterVisitorUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterVisitorUser", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.RegisterVisitorUserRequestBody Body;
        
        public RegisterVisitorUserRequest() {
        }
        
        public RegisterVisitorUserRequest(SFM.SFMWebservice.RegisterVisitorUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterVisitorUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ConfirmedPassword;
        
        public RegisterVisitorUserRequestBody() {
        }
        
        public RegisterVisitorUserRequestBody(string Name, string Surname, string Username, string Password, string Email, string ConfirmedPassword) {
            this.Name = Name;
            this.Surname = Surname;
            this.Username = Username;
            this.Password = Password;
            this.Email = Email;
            this.ConfirmedPassword = ConfirmedPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterVisitorUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterVisitorUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.RegisterVisitorUserResponseBody Body;
        
        public RegisterVisitorUserResponse() {
        }
        
        public RegisterVisitorUserResponse(SFM.SFMWebservice.RegisterVisitorUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterVisitorUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegisterVisitorUserResult;
        
        public RegisterVisitorUserResponseBody() {
        }
        
        public RegisterVisitorUserResponseBody(int RegisterVisitorUserResult) {
            this.RegisterVisitorUserResult = RegisterVisitorUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUser", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginUserRequestBody Body;
        
        public LoginUserRequest() {
        }
        
        public LoginUserRequest(SFM.SFMWebservice.LoginUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginUserRequestBody() {
        }
        
        public LoginUserRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginUserResponseBody Body;
        
        public LoginUserResponse() {
        }
        
        public LoginUserResponse(SFM.SFMWebservice.LoginUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginUserResult;
        
        public LoginUserResponseBody() {
        }
        
        public LoginUserResponseBody(int LoginUserResult) {
            this.LoginUserResult = LoginUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAdmin", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginAdminRequestBody Body;
        
        public LoginAdminRequest() {
        }
        
        public LoginAdminRequest(SFM.SFMWebservice.LoginAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginAdminRequestBody() {
        }
        
        public LoginAdminRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginAdminResponseBody Body;
        
        public LoginAdminResponse() {
        }
        
        public LoginAdminResponse(SFM.SFMWebservice.LoginAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginAdminResult;
        
        public LoginAdminResponseBody() {
        }
        
        public LoginAdminResponseBody(int LoginAdminResult) {
            this.LoginAdminResult = LoginAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginManagerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginManager", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginManagerRequestBody Body;
        
        public LoginManagerRequest() {
        }
        
        public LoginManagerRequest(SFM.SFMWebservice.LoginManagerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginManagerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginManagerRequestBody() {
        }
        
        public LoginManagerRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginManagerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginManagerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginManagerResponseBody Body;
        
        public LoginManagerResponse() {
        }
        
        public LoginManagerResponse(SFM.SFMWebservice.LoginManagerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginManagerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginManagerResult;
        
        public LoginManagerResponseBody() {
        }
        
        public LoginManagerResponseBody(int LoginManagerResult) {
            this.LoginManagerResult = LoginManagerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginConsultantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginConsultant", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginConsultantRequestBody Body;
        
        public LoginConsultantRequest() {
        }
        
        public LoginConsultantRequest(SFM.SFMWebservice.LoginConsultantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginConsultantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginConsultantRequestBody() {
        }
        
        public LoginConsultantRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginConsultantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginConsultantResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginConsultantResponseBody Body;
        
        public LoginConsultantResponse() {
        }
        
        public LoginConsultantResponse(SFM.SFMWebservice.LoginConsultantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginConsultantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginConsultantResult;
        
        public LoginConsultantResponseBody() {
        }
        
        public LoginConsultantResponseBody(int LoginConsultantResult) {
            this.LoginConsultantResult = LoginConsultantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCustomer", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginCustomerRequestBody Body;
        
        public LoginCustomerRequest() {
        }
        
        public LoginCustomerRequest(SFM.SFMWebservice.LoginCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginCustomerRequestBody() {
        }
        
        public LoginCustomerRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.LoginCustomerResponseBody Body;
        
        public LoginCustomerResponse() {
        }
        
        public LoginCustomerResponse(SFM.SFMWebservice.LoginCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginCustomerResult;
        
        public LoginCustomerResponseBody() {
        }
        
        public LoginCustomerResponseBody(int LoginCustomerResult) {
            this.LoginCustomerResult = LoginCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterEmployee", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.RegisterEmployeeRequestBody Body;
        
        public RegisterEmployeeRequest() {
        }
        
        public RegisterEmployeeRequest(SFM.SFMWebservice.RegisterEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmpType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email;
        
        public RegisterEmployeeRequestBody() {
        }
        
        public RegisterEmployeeRequestBody(string EmpType, string Name, string Surname, string Email) {
            this.EmpType = EmpType;
            this.Name = Name;
            this.Surname = Surname;
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.RegisterEmployeeResponseBody Body;
        
        public RegisterEmployeeResponse() {
        }
        
        public RegisterEmployeeResponse(SFM.SFMWebservice.RegisterEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegisterEmployeeResult;
        
        public RegisterEmployeeResponseBody() {
        }
        
        public RegisterEmployeeResponseBody(int RegisterEmployeeResult) {
            this.RegisterEmployeeResult = RegisterEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEmployee", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.RemoveEmployeeRequestBody Body;
        
        public RemoveEmployeeRequest() {
        }
        
        public RemoveEmployeeRequest(SFM.SFMWebservice.RemoveEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmpType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmployeeUsername;
        
        public RemoveEmployeeRequestBody() {
        }
        
        public RemoveEmployeeRequestBody(string EmpType, string EmployeeUsername) {
            this.EmpType = EmpType;
            this.EmployeeUsername = EmployeeUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.RemoveEmployeeResponseBody Body;
        
        public RemoveEmployeeResponse() {
        }
        
        public RemoveEmployeeResponse(SFM.SFMWebservice.RemoveEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveEmployeeResult;
        
        public RemoveEmployeeResponseBody() {
        }
        
        public RemoveEmployeeResponseBody(bool RemoveEmployeeResult) {
            this.RemoveEmployeeResult = RemoveEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditEmployeeInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditEmployeeInformation", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.EditEmployeeInformationRequestBody Body;
        
        public EditEmployeeInformationRequest() {
        }
        
        public EditEmployeeInformationRequest(SFM.SFMWebservice.EditEmployeeInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditEmployeeInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmpType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmployeeUsername;
        
        public EditEmployeeInformationRequestBody() {
        }
        
        public EditEmployeeInformationRequestBody(string EmpType, string EmployeeUsername) {
            this.EmpType = EmpType;
            this.EmployeeUsername = EmployeeUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditEmployeeInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditEmployeeInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SFM.SFMWebservice.EditEmployeeInformationResponseBody Body;
        
        public EditEmployeeInformationResponse() {
        }
        
        public EditEmployeeInformationResponse(SFM.SFMWebservice.EditEmployeeInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditEmployeeInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditEmployeeInformationResult;
        
        public EditEmployeeInformationResponseBody() {
        }
        
        public EditEmployeeInformationResponseBody(bool EditEmployeeInformationResult) {
            this.EditEmployeeInformationResult = EditEmployeeInformationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SFMConsultingWebServiceSoapChannel : SFM.SFMWebservice.SFMConsultingWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SFMConsultingWebServiceSoapClient : System.ServiceModel.ClientBase<SFM.SFMWebservice.SFMConsultingWebServiceSoap>, SFM.SFMWebservice.SFMConsultingWebServiceSoap {
        
        public SFMConsultingWebServiceSoapClient() {
        }
        
        public SFMConsultingWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SFMConsultingWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFMConsultingWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFMConsultingWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.RegisterVisitorUserResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.RegisterVisitorUser(SFM.SFMWebservice.RegisterVisitorUserRequest request) {
            return base.Channel.RegisterVisitorUser(request);
        }
        
        public int RegisterVisitorUser(string Name, string Surname, string Username, string Password, string Email, string ConfirmedPassword) {
            SFM.SFMWebservice.RegisterVisitorUserRequest inValue = new SFM.SFMWebservice.RegisterVisitorUserRequest();
            inValue.Body = new SFM.SFMWebservice.RegisterVisitorUserRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Email = Email;
            inValue.Body.ConfirmedPassword = ConfirmedPassword;
            SFM.SFMWebservice.RegisterVisitorUserResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).RegisterVisitorUser(inValue);
            return retVal.Body.RegisterVisitorUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.RegisterVisitorUserResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.RegisterVisitorUserAsync(SFM.SFMWebservice.RegisterVisitorUserRequest request) {
            return base.Channel.RegisterVisitorUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.RegisterVisitorUserResponse> RegisterVisitorUserAsync(string Name, string Surname, string Username, string Password, string Email, string ConfirmedPassword) {
            SFM.SFMWebservice.RegisterVisitorUserRequest inValue = new SFM.SFMWebservice.RegisterVisitorUserRequest();
            inValue.Body = new SFM.SFMWebservice.RegisterVisitorUserRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Email = Email;
            inValue.Body.ConfirmedPassword = ConfirmedPassword;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).RegisterVisitorUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.LoginUserResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginUser(SFM.SFMWebservice.LoginUserRequest request) {
            return base.Channel.LoginUser(request);
        }
        
        public int LoginUser(string Username, string Password) {
            SFM.SFMWebservice.LoginUserRequest inValue = new SFM.SFMWebservice.LoginUserRequest();
            inValue.Body = new SFM.SFMWebservice.LoginUserRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            SFM.SFMWebservice.LoginUserResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginUser(inValue);
            return retVal.Body.LoginUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginUserResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginUserAsync(SFM.SFMWebservice.LoginUserRequest request) {
            return base.Channel.LoginUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.LoginUserResponse> LoginUserAsync(string Username, string Password) {
            SFM.SFMWebservice.LoginUserRequest inValue = new SFM.SFMWebservice.LoginUserRequest();
            inValue.Body = new SFM.SFMWebservice.LoginUserRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.LoginAdminResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginAdmin(SFM.SFMWebservice.LoginAdminRequest request) {
            return base.Channel.LoginAdmin(request);
        }
        
        public int LoginAdmin(string Username, string Password) {
            SFM.SFMWebservice.LoginAdminRequest inValue = new SFM.SFMWebservice.LoginAdminRequest();
            inValue.Body = new SFM.SFMWebservice.LoginAdminRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            SFM.SFMWebservice.LoginAdminResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginAdmin(inValue);
            return retVal.Body.LoginAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginAdminResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginAdminAsync(SFM.SFMWebservice.LoginAdminRequest request) {
            return base.Channel.LoginAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.LoginAdminResponse> LoginAdminAsync(string Username, string Password) {
            SFM.SFMWebservice.LoginAdminRequest inValue = new SFM.SFMWebservice.LoginAdminRequest();
            inValue.Body = new SFM.SFMWebservice.LoginAdminRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.LoginManagerResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginManager(SFM.SFMWebservice.LoginManagerRequest request) {
            return base.Channel.LoginManager(request);
        }
        
        public int LoginManager(string Username, string Password) {
            SFM.SFMWebservice.LoginManagerRequest inValue = new SFM.SFMWebservice.LoginManagerRequest();
            inValue.Body = new SFM.SFMWebservice.LoginManagerRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            SFM.SFMWebservice.LoginManagerResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginManager(inValue);
            return retVal.Body.LoginManagerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginManagerResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginManagerAsync(SFM.SFMWebservice.LoginManagerRequest request) {
            return base.Channel.LoginManagerAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.LoginManagerResponse> LoginManagerAsync(string Username, string Password) {
            SFM.SFMWebservice.LoginManagerRequest inValue = new SFM.SFMWebservice.LoginManagerRequest();
            inValue.Body = new SFM.SFMWebservice.LoginManagerRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginManagerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.LoginConsultantResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginConsultant(SFM.SFMWebservice.LoginConsultantRequest request) {
            return base.Channel.LoginConsultant(request);
        }
        
        public int LoginConsultant(string Username, string Password) {
            SFM.SFMWebservice.LoginConsultantRequest inValue = new SFM.SFMWebservice.LoginConsultantRequest();
            inValue.Body = new SFM.SFMWebservice.LoginConsultantRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            SFM.SFMWebservice.LoginConsultantResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginConsultant(inValue);
            return retVal.Body.LoginConsultantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginConsultantResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginConsultantAsync(SFM.SFMWebservice.LoginConsultantRequest request) {
            return base.Channel.LoginConsultantAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.LoginConsultantResponse> LoginConsultantAsync(string Username, string Password) {
            SFM.SFMWebservice.LoginConsultantRequest inValue = new SFM.SFMWebservice.LoginConsultantRequest();
            inValue.Body = new SFM.SFMWebservice.LoginConsultantRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginConsultantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.LoginCustomerResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginCustomer(SFM.SFMWebservice.LoginCustomerRequest request) {
            return base.Channel.LoginCustomer(request);
        }
        
        public int LoginCustomer(string Username, string Password) {
            SFM.SFMWebservice.LoginCustomerRequest inValue = new SFM.SFMWebservice.LoginCustomerRequest();
            inValue.Body = new SFM.SFMWebservice.LoginCustomerRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            SFM.SFMWebservice.LoginCustomerResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginCustomer(inValue);
            return retVal.Body.LoginCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.LoginCustomerResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.LoginCustomerAsync(SFM.SFMWebservice.LoginCustomerRequest request) {
            return base.Channel.LoginCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.LoginCustomerResponse> LoginCustomerAsync(string Username, string Password) {
            SFM.SFMWebservice.LoginCustomerRequest inValue = new SFM.SFMWebservice.LoginCustomerRequest();
            inValue.Body = new SFM.SFMWebservice.LoginCustomerRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).LoginCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.RegisterEmployeeResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.RegisterEmployee(SFM.SFMWebservice.RegisterEmployeeRequest request) {
            return base.Channel.RegisterEmployee(request);
        }
        
        public int RegisterEmployee(string EmpType, string Name, string Surname, string Email) {
            SFM.SFMWebservice.RegisterEmployeeRequest inValue = new SFM.SFMWebservice.RegisterEmployeeRequest();
            inValue.Body = new SFM.SFMWebservice.RegisterEmployeeRequestBody();
            inValue.Body.EmpType = EmpType;
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Email = Email;
            SFM.SFMWebservice.RegisterEmployeeResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).RegisterEmployee(inValue);
            return retVal.Body.RegisterEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.RegisterEmployeeResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.RegisterEmployeeAsync(SFM.SFMWebservice.RegisterEmployeeRequest request) {
            return base.Channel.RegisterEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.RegisterEmployeeResponse> RegisterEmployeeAsync(string EmpType, string Name, string Surname, string Email) {
            SFM.SFMWebservice.RegisterEmployeeRequest inValue = new SFM.SFMWebservice.RegisterEmployeeRequest();
            inValue.Body = new SFM.SFMWebservice.RegisterEmployeeRequestBody();
            inValue.Body.EmpType = EmpType;
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Email = Email;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).RegisterEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.RemoveEmployeeResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.RemoveEmployee(SFM.SFMWebservice.RemoveEmployeeRequest request) {
            return base.Channel.RemoveEmployee(request);
        }
        
        public bool RemoveEmployee(string EmpType, string EmployeeUsername) {
            SFM.SFMWebservice.RemoveEmployeeRequest inValue = new SFM.SFMWebservice.RemoveEmployeeRequest();
            inValue.Body = new SFM.SFMWebservice.RemoveEmployeeRequestBody();
            inValue.Body.EmpType = EmpType;
            inValue.Body.EmployeeUsername = EmployeeUsername;
            SFM.SFMWebservice.RemoveEmployeeResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).RemoveEmployee(inValue);
            return retVal.Body.RemoveEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.RemoveEmployeeResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.RemoveEmployeeAsync(SFM.SFMWebservice.RemoveEmployeeRequest request) {
            return base.Channel.RemoveEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.RemoveEmployeeResponse> RemoveEmployeeAsync(string EmpType, string EmployeeUsername) {
            SFM.SFMWebservice.RemoveEmployeeRequest inValue = new SFM.SFMWebservice.RemoveEmployeeRequest();
            inValue.Body = new SFM.SFMWebservice.RemoveEmployeeRequestBody();
            inValue.Body.EmpType = EmpType;
            inValue.Body.EmployeeUsername = EmployeeUsername;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).RemoveEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFM.SFMWebservice.EditEmployeeInformationResponse SFM.SFMWebservice.SFMConsultingWebServiceSoap.EditEmployeeInformation(SFM.SFMWebservice.EditEmployeeInformationRequest request) {
            return base.Channel.EditEmployeeInformation(request);
        }
        
        public bool EditEmployeeInformation(string EmpType, string EmployeeUsername) {
            SFM.SFMWebservice.EditEmployeeInformationRequest inValue = new SFM.SFMWebservice.EditEmployeeInformationRequest();
            inValue.Body = new SFM.SFMWebservice.EditEmployeeInformationRequestBody();
            inValue.Body.EmpType = EmpType;
            inValue.Body.EmployeeUsername = EmployeeUsername;
            SFM.SFMWebservice.EditEmployeeInformationResponse retVal = ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).EditEmployeeInformation(inValue);
            return retVal.Body.EditEmployeeInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SFM.SFMWebservice.EditEmployeeInformationResponse> SFM.SFMWebservice.SFMConsultingWebServiceSoap.EditEmployeeInformationAsync(SFM.SFMWebservice.EditEmployeeInformationRequest request) {
            return base.Channel.EditEmployeeInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SFM.SFMWebservice.EditEmployeeInformationResponse> EditEmployeeInformationAsync(string EmpType, string EmployeeUsername) {
            SFM.SFMWebservice.EditEmployeeInformationRequest inValue = new SFM.SFMWebservice.EditEmployeeInformationRequest();
            inValue.Body = new SFM.SFMWebservice.EditEmployeeInformationRequestBody();
            inValue.Body.EmpType = EmpType;
            inValue.Body.EmployeeUsername = EmployeeUsername;
            return ((SFM.SFMWebservice.SFMConsultingWebServiceSoap)(this)).EditEmployeeInformationAsync(inValue);
        }
    }
}
